name: tfsec

on:
  pull_request:
    paths:
      - 'terraform/**'
  push:
    paths:
      - 'terraform/**'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        continue-on-error: true
        with:
          working_directory: terraform